### ISSUE TITLE
Add data toggle validator and respective data errors for all the apps

### ISSUE THREAD

**Issue by kavithaenair** [fossasia/apps.loklak.org#148]
- Issue type: Bug Report

### Short description
Most of the apps in apps.loklak.org is supporting blank searches and showing results for undefined.

### Expected Behaviour
So here we can add a validator and display respective error messages when clicked on search button or when one of the field is skipped.

**Comment by kavithaenair** [comment]
i want to fix this @daminisatya @mariobehling

**Comment by djmgit** [comment]
@kavithaenair thats great! go for it.

I was thinking that, rather than adding validators for individual apps validating function could be added to loklak.js file or a separate js file which could be used by all the apps.This will prevent code repeatation.Future apps could use these functions.
For this we need to find out what validations we require. For eg : date is used in many apps, so we can use a function to validate dates.
I have added a function in whatsTrending/app.js to validate dates, you could reuse that if you want.
what do you feel? @daminisatya  @mariobehling

**Comment by kavithaenair** [comment]
@djmgit i thought to add autofocus/required and patterns to the html tags. What do you think?
And as far as date is concerned we can change the type to date type so that calendar will be displayed , so is easy for user as he can select the date instead of typing it.

**Comment by djmgit** [comment]
@kavithaenair sounds good. Nice about date. Just one think making the input type field does not always works on firefox, but works on chrome (the calender). Jquery calender may help.
