### ISSUE TITLE
Create a tutorial for creating loklak apps

### ISSUE THREAD

**Issue by djmgit** [fossasia/apps.loklak.org#175]
Create a tutorial page which will contain detailed information about creating loklakapps. Detailed information about configuring the app.json should be mentioned here. Sample app.json should be provied.

**Comment by djmgit** [comment]
I am working on it

**Comment by djmgit** [comment]
I am working on it

**Comment by mariobehling** [comment]
All documentation should go into the docs folder. Documentation will be rendered with yaydocs in future.

**Comment by djmgit** [comment]
@mariobehling I have been working on a tutorial page (as a part of my GSOC proposal) 
Here is the prototype link : http://loklakapps.surge.sh/tutorial/ 
(work is left)
Should I also create corresponding .md files and add it to docs folder?

**Comment by djmgit** [comment]
I have tried to provide as much details as possible for creating a loklak app

**Comment by mariobehling** [comment]
Documentation is important. The details of proposals always need to be aligned with projects. 

All documentation in FOSSASIA projects follows the same pattern A) most important points go into the Readme.md B) Everything else goes into the /docs folder.

The yaydoc project will take care of generating documentation and themes can be added in that project. The yaydoc devs should definitely work together with all projects.

Just to ensure, there is an alignment: Please read again the first emails sent to accepted GSoC students as well as the guidelines about the role of proposals. Because proposals get accepted does not mean they can be implemented without any changes. They always need to align with the ongoing changes and development flow of project.

**Comment by mariobehling** [comment]
Documentation of loklak projects will be rendered from the actual source repositories and go into one place: http://dev.loklak.org

We don't want to scatter documentation at different places. Please only store documentation in the standard locations.

**Comment by djmgit** [comment]
@mariobehling okay, so I will create the corresponding markdown and put it in docs folder, and  should I keep this tutorial page (http://loklakapps.surge.sh/tutorial/) for the time being or do not include it in my PR at all ?
