### ISSUE TITLE
Emoji Heatmapper - Heatmap? Propose and implement heatmap display

### ISSUE THREAD

**Issue by mariobehling** [fossasia/apps.loklak.org#206]
There are different ways to make a heatmap. Right now the implementation seems to be to show all emojis on a map. This is not a heatmap in the original sense.

Please propose and implement an additional way to show the heatmap using emoji data in the original sense of a heatmap. A quick search on Google shows mostly examples similar to the following:
https://www.youtube.com/watch?v=9Qv7F_43dOk
https://www.youtube.com/watch?v=eepKvmknGr8
![twitter-heat-map](https://user-images.githubusercontent.com/1583873/27373416-7c27d2e6-5668-11e7-8101-f31e607ce9dd.png)

![mapsmania](https://user-images.githubusercontent.com/1583873/27373274-f675d95e-5667-11e7-97ae-15da8202b5b2.gif)

![r-twitter-heat-map-large570](https://user-images.githubusercontent.com/1583873/27373275-f6787ce0-5667-11e7-9d86-cab81fb0e5a1.jpg)

**Comment by kavithaenair** [comment]
@mariobehling so here i was thinking that instead of getting heatmap for a particular emoji on search, what if when we open the app and it shows occurrences of all emojis on the map as heatmap. We can also add two options, where in one shows occurrences of all the emojis on heatmap and the other option should ask the user for the input.
